site_name: "SFK: Explainable AI Toolkit"
nav:
  - Welcome: 1.Welcome.ipynb
  - Data: 2.Data.ipynb
  - Models: 3.Models.ipynb
  # - Geospatial: 4.Geospatial.ipynb
  - Language: 5.Language.ipynb

plugins:
    - mkdocs-jupyter:
    # show_input: False

theme:
  name: material

  palette:
    primary: teal

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.prune 

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format